name: CI

on: [push]

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - uses: actions/checkout@v1
    - name: Build
      run: |
        git submodule update --init --recursive
        nuget restore de4dot.sln
        msbuild de4dot.sln /p:Configuration=Release /m /verbosity:normal /p:WarningLevel=0
    - name: Create ZIP
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        Compress-Archive -Path Release/* -DestinationPath de4dot-cex
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: de4dot-cex.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}